---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:16.13.1
    commands:
      - yarn install
      - yarn run build
    when:
      event:
        - push
        - tag

  - name: upload-test-to-oss
    image: jacie/drone-aliyun-oss
    pull: always
    environment:
      ALIYUN_ACCESS_KEY_ID:
        from_secret: aliyun_access_id
      ALIYUN_SECRET_ACCESS_KEY:
        from_secret: aliyun_access_secret
      PLUGIN_SOURCE: ./dist
      ALIYUN_BUCKET: oss://dev-tool
      ALIYUN_ENDPOINT: http://oss-cn-shenzhen.aliyuncs.com
      PLUGIN_TARGET: tencent-operator-tke
      PLUGIN_RECURSIVE: -r
      PLUGIN_ACCESS: public-read
    commands:
      - "aliyun-oss"
    when:
      event:
        - push

  - name: deployment-to-oss
    image: jacie/drone-aliyun-oss
    pull: always
    environment:
      ALIYUN_ACCESS_KEY_ID:
        from_secret: aliyun_access_id
      ALIYUN_SECRET_ACCESS_KEY:
        from_secret: aliyun_access_secret
      PLUGIN_SOURCE: ./dist
      ALIYUN_BUCKET: oss://rancher2-drivers
      ALIYUN_ENDPOINT: http://oss-cn-beijing.aliyuncs.com
      PLUGIN_TARGET: pandaria/ui/cluster-operator-tencent/${DRONE_TAG}
      PLUGIN_RECURSIVE: -r
      PLUGIN_ACCESS: public-read
    commands:
      - "aliyun-oss"
    when:
      event:
        - tag

  - name: github_binary_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
      files:
        - dist/*
      prerelease: true
      title: "Pre-release ${DRONE_TAG}"
    when:
      event:
        - tag

node:
  instance: agent-amd64
