name: Push to Master

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v*.*.*' # Matches any tag that starts with 'v' and follows semantic versioning
      - 'v*.*.*-rc*'

permissions:
  contents: write # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/gallium
      - name: build
        run: |
          yarn install
          yarn run build
      - name: checksum
        if: startsWith(github.ref,'regs/tags/')
        run: |
          sha256sum dist/* > dist/sha256sum.txt
      - name: Release
        if: startsWith(github.ref,'regs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REPO || github.repository }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
      - name: Push dev container
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
